### ISSUE TITLE
Issue for Review

### ISSUE THREAD

**Issue by OmarMWarraich** [OmarMWarraich/group-capstone#21]
@mohamed20163858 and  @normainobary2021 
 
The link to our capstone project is as follows:
https://github.com/OmarMWarraich/group-capstone/projects/1

Kindly note that there are three members in our team.

**Comment by Nemwel-Boniface** [comment]
## Hello @OmarMWarraich          :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 


There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] Kindly include a link to your Kanban board in the Issue link and request for a review.

![image](https://user-images.githubusercontent.com/86318284/189885968-1cf705ba-dd76-4cea-a285-a26222d0b95a.png)


_Check the comments under the review._

## [Optional] suggestions

- [ ] It would be a good thing to also tag your other group members in this issue

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by leonardodiasb** [comment]
# Status: ✔️ Project Approved ✔️ 

Hello @OmarMWarraich 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can start your project 🚀 

## Highlights

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OmarMWarraich** [comment]
The project has been approved, therefore, I am closing this issue.
